@startuml association
left to right direction

class Order {
  + id: int
  + date: date
}

class Customer {
  + id: int
  + name: str
  + address: str
}

class OrderItem {
  + id: int
  + quantity: int
}

Customer "1" --> "0..*" Order: places
Order "1" --> "0..*" OrderItem: contains
@enduml
